### ISSUE TITLE
I give up

### ISSUE THREAD

**Issue by mintminty59** [crombiecrunch/yiimp#2]
Script seemed to work ok, I have checked /var/ no web folder exists

I searched for serverconfig.php doesnt exist 

keys.php does

ubuntu@ubuntu:~$ ./main.sh
bash: ./main.sh: No such file or directory
ubuntu@ubuntu:~$ ./loop2.sh
bash: ./loop2.sh: No such file or directory
ubuntu@ubuntu:~$ ./block.sh
bash: ./block.sh: No such file or directory
ubuntu@ubuntu:~$

**Comment by mintminty59** [comment]
tried a 2nd time and saw this error

/tmp/ccCYkRRB.s:128: Error: bad instruction `bswapl r3'
Makefile:55: recipe for target 'coind_template.o' failed
make: *** [coind_template.o] Error 1
cp: cannot stat 'stratum': No such file or directory
sed: -e expression #1, char 17: unknown option to `s'
chmod: cannot access 'run.sh': No such file or directory
Update default timezone.
Thanks for using this installation script. Donations welcome

**Comment by mintminty59** [comment]
Peforming the SQL import

ERROR 1060 (42S21) at line 3: Duplicate column name 'login'
ERROR 1060 (42S21) at line 4: Duplicate column name 'hostaddr'
ERROR 1060 (42S21) at line 3: Duplicate column name 'hasmasternodes'
ERROR 1060 (42S21) at line 7: Duplicate column name 'serveruser'
ERROR 1060 (42S21) at line 3: Duplicate column name 'workerid'
ERROR 1060 (42S21) at line 3: Duplicate column name 'errmsg'
ERROR 1060 (42S21) at line 7: Duplicate column name 'share_diff'
ERROR 1060 (42S21) at line 4: Duplicate column name 'disabled'
ERROR 1060 (42S21) at line 5: Duplicate column name 'priority'
ERROR 1060 (42S21) at line 6: Duplicate column name 'ontrade'
ERROR 1060 (42S21) at line 7: Duplicate column name 'balancetime'
ERROR 1060 (42S21) at line 8: Duplicate column name 'pricetime'
ERROR 1060 (42S21) at line 6: Duplicate column name 'rpcssl'
ERROR 1060 (42S21) at line 7: Duplicate column name 'rpccurl'
ERROR 1060 (42S21) at line 8: Duplicate column name 'rpccert'
ERROR 1060 (42S21) at line 9: Duplicate column name 'account'
ERROR 1060 (42S21) at line 10: Duplicate column name 'payout_min'
ERROR 1060 (42S21) at line 11: Duplicate column name 'payout_max'
ERROR 1060 (42S21) at line 12: Duplicate column name 'link_site'
ERROR 1061 (42000) at line 14: Duplicate key name 'created'
ERROR 1054 (42S22) at line 4: Unknown column 'last_login' in 'accounts'
ERROR 1061 (42000) at line 6: Duplicate key name 'earning'

**Comment by crombiecrunch** [comment]
join me over on https://discord.gg/uQ5wdTC

**Comment by topip** [comment]
Hello! Run the .sh files from "/ var / www / xxx / html / web" and it is marked with the following message:
Mon Aug 28 15:49:30 UTC 2017
Started in / var / www / xxx / html / web
"

And black screen ... there is no service .. what do I do?

**Comment by topip** [comment]
● nginx.service - A high performance web server and a reverse proxy server
   Loaded: loaded (/lib/systemd/system/nginx.service; enabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Mon 2017-08-28 16:21:56 UTC; 18s ago
  Process: 5284 ExecStop=/sbin/start-stop-daemon --quiet --stop --retry QUIT/5 --pidfile /run/nginx.pid (code
  Process: 2386 ExecStart=/usr/sbin/nginx -g daemon on; master_process on; (code=exited, status=0/SUCCESS)
  Process: 6350 ExecStartPre=/usr/sbin/nginx -t -q -g daemon on; master_process on; (code=exited, status=1/FA
 Main PID: 2389 (code=exited, status=0/SUCCESS)

Aug 28 16:21:56 ip-172-31-30-253 systemd[1]: Stopped A high performance web server and a reverse proxy server
Aug 28 16:21:56 ip-172-31-30-253 systemd[1]: Starting A high performance web server and a reverse proxy serve
Aug 28 16:21:56 ip-172-31-30-253 nginx[6350]: nginx: [emerg] BIO_new_file("/etc/letsencrypt/live/blotz.shop/f
Aug 28 16:21:56 ip-172-31-30-253 nginx[6350]: nginx: configuration file /etc/nginx/nginx.conf test failed
Aug 28 16:21:56 ip-172-31-30-253 systemd[1]: nginx.service: Control process exited, code=exited status=1
Aug 28 16:21:56 ip-172-31-30-253 systemd[1]: Failed to start A high performance web server and a reverse prox
Aug 28 16:21:56 ip-172-31-30-253 systemd[1]: nginx.service: Unit entered failed state.
Aug 28 16:21:56 ip-172-31-30-253 systemd[1]: nginx.service: Failed with result 'exit-code'.
